services:
  app:
    build: .
    container_name: app
    ports:
      - 5000:5000
    tty: true
    volumes:
      - .:/usr/src/
    command: flask run --host=0.0.0.0
    depends_on:
      - db

  db:
    image: mysql:5.7
    container_name: db
    env_file: .env # 環境変数の定義に.envを利用
    ports:
      - "3306:3306" #ポート番号の設定
    volumes:
      - ./docker/db/initdb:/docker-entrypoint-initdb.d
      - ./my.cnf:/etc/mysql/conf.d/my.cnf
